name: depi_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  animate_do: ^3.0.2
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  shared_preferences: ^2.5.3
  awesome_snackbar_content: ^0.1.7
  bloc: ^9.0.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.2
  modal_progress_hud_nsn: ^0.5.1
  flutter_phone_direct_caller: ^2.2.1
  flutter_dotenv: ^6.0.0
  video_thumbnail: ^0.5.6
  uuid: ^4.5.1
  skeletonizer: ^2.1.0+1
  dio: ^5.9.0
  image_picker: ^1.2.0
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - .env
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"